spring: 
  name: testweb2
 
  profiles:
    default: dev-k8s
  
  main:
    allow-bean-definition-overriding: true  # 수동 Bean이 자동 Bean을 오버라이딩하게 설정
  
  jpa:
    open-in-view: false 
      # open-in-view(혹은 Open-Session-In-View(OSIV))
      # true(기본값) : 사용자에게 응답 또는 view가 렌더링될 때까지 영속성 컨텍스트 유지
      # false : 트랜젝션이 종료될 때 영속성 컨텍스트 종료
        
  #HDS
  #Html Reload
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/thymeleaf/

  #Css, Js Reload
  web:
    resources:
      static-locations: file:src/main/resources/static/
